export const copy = {
  hi: {
    brandTag: 'माँ और बच्चों के लिए आसान पढ़ाई',
    settingsLabel: 'Session settings',
    chatsLabel: 'चैट्स',
    newChatLabel: 'नई चैट',
    settingsShort: 'सेटिंग्स',
    activeNow: 'अभी बात करने के लिए तैयार',
    noChatsYet: 'अभी कोई पुरानी चैट नहीं',
    welcomeMessage:
      'नमस्ते। बच्चा mic दबाकर सवाल पूछे या होमवर्क की फोटो भेजे। मैं आसान हिन्दी में समझाऊँगी और फिर एक छोटा सवाल भी पूछूँगी।',
    readyHint: 'बच्चा बोले या फोटो भेजे।',
    listeningNow: 'मैं सुन रही हूँ...',
    transcribing: 'आवाज़ समझ रही हूँ...',
    processing: 'समझ रही हूँ...',
    tapHint: 'Mic दबाएँ या फोटो जोड़ें',
    unsupported: 'Mic की permission दें और Chrome में खोलकर फिर कोशिश करें।',
    startListening: 'बोलना शुरू करें',
    stopListening: 'सुनना बंद करें',
    retrySimple: 'और आसान करके',
    stopAudio: 'आवाज़ बंद',
    uploadImage: 'फोटो जोड़ें',
    imageHelp: 'होमवर्क, किताब, worksheet, या question की फोटो भेजें',
    voiceModeLabel: 'बोलकर पूछें',
    uploadLabel: 'फोटो',
    cameraLabel: 'कैमरा',
    cameraHint: 'खींचते ही पूछेंगे',
    starterTitle: 'आज क्या पूछना है?',
    starterHelp: 'बच्चा इनमें से एक दबा सकता है या mic दबाकर बोल सकता है।',
    starterAskMath: '10 + 10 क्या होता है?',
    starterAskHindi: 'संज्ञा क्या होती है?',
    starterAskEvs: 'पेड़ को पानी क्यों चाहिए?',
    childAsked: 'बच्चे ने पूछा',
    tutorReplied: 'NanhiPathshala ने जवाब दिया',
    playReply: 'सुनें',
    showText: 'लिखा हुआ देखें',
    motherSummary: 'माँ के लिए note',
    imageSent: 'फोटो भेजी गई',
    classTitle: 'कक्षा',
    subjectTitle: 'विषय',
    moodTitle: 'mood',
    errorFallback: 'अभी जवाब नहीं आ पाया। दोबारा कोशिश करें।',
  },
  en: {
    brandTag: 'Easy learning for mothers and children',
    settingsLabel: 'Session settings',
    chatsLabel: 'Chats',
    newChatLabel: 'New chat',
    settingsShort: 'Settings',
    activeNow: 'Ready to talk now',
    noChatsYet: 'No saved chats yet',
    welcomeMessage:
      'Hello. Let the child tap the mic or send a homework photo. I will explain simply and then ask one small follow-up question.',
    readyHint: 'Let the child speak or upload an image.',
    listeningNow: 'I am listening...',
    transcribing: 'Understanding the voice...',
    processing: 'Understanding...',
    tapHint: 'Tap the mic or attach an image',
    unsupported: 'Mic input is not working properly in this browser. Try Chrome.',
    startListening: 'Start speaking',
    stopListening: 'Stop listening',
    retrySimple: 'Make it simpler',
    stopAudio: 'Stop audio',
    uploadImage: 'Add photo',
    imageHelp: 'Send a photo of homework, book, worksheet, or question',
    voiceModeLabel: 'Ask by voice',
    uploadLabel: 'Photo',
    cameraLabel: 'Camera',
    cameraHint: 'Ask right after capture',
    starterTitle: 'What should we ask today?',
    starterHelp: 'The child can tap one of these or use the mic.',
    starterAskMath: 'What is 10 + 10?',
    starterAskHindi: 'What is a noun?',
    starterAskEvs: 'Why do plants need water?',
    childAsked: 'Child asked',
    tutorReplied: 'NanhiPathshala replied',
    playReply: 'Play',
    showText: 'Show text',
    motherSummary: 'Note for mother',
    imageSent: 'Photo sent',
    classTitle: 'Class',
    subjectTitle: 'Subject',
    moodTitle: 'Mood',
    errorFallback: 'The answer could not be generated right now. Please try again.',
  },
} as const

export const subjects = [
  {
    id: 'math',
    label: { hi: 'गणित', en: 'Math' },
    topic: { hi: 'भिन्न', en: 'Fractions' },
    summary: {
      hi: 'आज गणित की बात आसान भाषा में समझाई गई।',
      en: 'Today a math concept was explained in simple language.',
    },
    nextPractice: {
      hi: 'रोटी या सेब को बराबर हिस्सों में बाँटकर बच्चे से पूछिए कौन-सा हिस्सा कितना है।',
      en: 'Cut a roti or apple into equal parts and ask the child what each part is.',
    },
  },
  {
    id: 'hindi',
    label: { hi: 'हिन्दी', en: 'Hindi' },
    topic: { hi: 'संज्ञा', en: 'Nouns' },
    summary: {
      hi: 'आज हिन्दी के शब्दों को घर के example से समझाया गया।',
      en: 'Today Hindi word concepts were explained using home examples.',
    },
    nextPractice: {
      hi: 'घर की 5 चीज़ों के नाम बुलवाइए।',
      en: 'Ask the child to name 5 things at home.',
    },
  },
  {
    id: 'evs',
    label: { hi: 'EVS', en: 'EVS' },
    topic: { hi: 'पौधों को पानी', en: 'Water for plants' },
    summary: {
      hi: 'आज EVS की बात रोज़मर्रा की चीज़ों से समझाई गई।',
      en: 'Today an EVS topic was explained through everyday examples.',
    },
    nextPractice: {
      hi: 'घर के पौधे को पानी देते समय बच्चे से पूछिए क्यों दे रहे हैं।',
      en: 'While watering a plant, ask the child why it needs water.',
    },
  },
  {
    id: 'english',
    label: { hi: 'English', en: 'English' },
    topic: { hi: 'This और That', en: 'This and That' },
    summary: {
      hi: 'आज English का एक छोटा concept आसान तरह से समझाया गया।',
      en: 'Today a small English concept was explained simply.',
    },
    nextPractice: {
      hi: 'पास और दूर की चीज़ दिखाकर बच्चे से This या That बुलवाइए।',
      en: 'Show near and far things and ask the child to say This or That.',
    },
  },
] as const
